version: "3.8"
services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data

      # https://hub.docker.com/_/postgres
      # Warning: scripts in /docker-entrypoint-initdb.d are only run if you start the container with a data directory that is empt
      - ./db:/docker-entrypoint-initdb.d/

    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_ROOT_USER}
      POSTGRES_PASSWORD: ${PG_ROOT_PASSWORD}
    ports:
      - "5444:5444"
    command: postgres -c 'max_connections=1000' -p 5444

volumes:
  db_data:
